openapi: 3.0.4
info:
  title: Parts Of Speech
  description: >-
    Parts Of Speech is a simple tool for extracting nouns, verbs, adjectives,
    adverbs, etc. from text. It returns the extracted words based on the part of
    speech specified.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/partsofspeech:
    post:
      summary: Extract Words
      description: Extract nouns, verbs, adjectives, adverbs, etc. from text
      operationId: partsofspeech
      parameters: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  partofspeech: verbs
                  result:
                    - located
                    - had
                    - visit
                    - packed up
                    - boarded
                    - bound
                  count: 6
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: The text to extract words from
                partofspeech:
                  type: string
                  description: The part of speech to extract
              required:
                - text
                - partofspeech
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
sampleRequest:
  text: >-
    My friend from college hails from a small countryside village located at the
    heart of the state. During the last summer vacation, I had an opportunity to
    visit my friend in his village. I packed up my belongings and boarded the
    bus bound for the village
  partofspeech: verbs
